name = "Yoinky 4"
author = "Prectriv"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeda929ac6dbdfc94c0b87aa5689f5d361983e325cda4c8578066a7719cac286"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
