name = "Yoinky 4"
author = "Prectriv"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3903d8e595da4176dc6ff3ec518dadb54762a43890aa7cdd33d3a56f292277d4"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
