name = "Yoinky 4"
author = "Prectriv"
version = "4.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d94af098f22bb133dcb238fd6b49cf9275ef8c96e4f5563bcacbc9c56a7c4270"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
datapack-folder = "global_packs/required_data"
