name = "Yoinky 4"
author = "Prectriv"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3b05b6e0bf377044028f2e09950d0787a8e164a6dcaabc68597afe99b12f933"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
datapack-folder = "global_packs/required_data"
