name = "Yoinky 4"
author = "Prectriv"
version = "4.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9bac0d632b804638514d2bea8815a41556edf30bbc46c2ab2422c898b3c86dd"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
datapack-folder = "global_packs/required_data"
