name = "Yoinky 4"
author = "Prectriv"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e06ae4b0929a28c7760e0be826ca68706c4d592bead1f6edcd731592f1a9c81c"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
