name = "Yoinky 4"
author = "Prectriv"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c83e94a9ffe5ba49a2e15b3dfa4626af5595fc8c49a9695d3b6d51ded7e16f37"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
