name = "Yoinky 4"
author = "Prectriv"
version = "4.0.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "893819fbf6d582dac4ddd314f286e224d17be31ef624f4043b147fd99216f817"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
datapack-folder = "global_packs/required_data"
