name = "New Poinky 3D XS"
author = "prectriv"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69db853c58af19fe9ee13f5738d53156a0d4ccb100edac4eec4d8eddd1423013"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
datapack-folder = "./datapacks"
