name = "Poinky"
author = "prectriv"
version = "1.0.0-rc4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2558fb6d2e017efb4a73823315e04fbc61d4b533ed1d4372133ad61873c650bc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
datapack-folder = "./datapacks"
