name = "Poinky"
author = "prectriv"
version = "1.0.0-rc4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5947b95e6ea3f7971f90931e6491e036f7a28bbd96040a63f9ce4daa194ced0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
datapack-folder = "./datapacks"
