name = "Yoinky 3"
author = "Prectriv"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bb0c08ab494ed5dba6b6eff282c07b5d8053a695340085cb2239efbf252952e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
