name = "Yoinky 3"
author = "Prectriv"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38f7b0408472fb84ffcdffcbb2c4ae4ce08b2c7a74544dbbcf46155954fd2047"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
