name = "Yoinky 3"
author = "Prectriv"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b1885f1728bde278984d3698ff8fe9685a3dc34e65530aaf646cb2a8e8ab8ac"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
