name = "Yoinky 3"
author = "Prectriv"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9440b05dcfce89f2eb9e27e5db4089d0bfd9a0c30042f2f1d5db2a9d39d2a4de"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
