name = "Yoinky 3"
author = "Prectriv"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "109ee9570f3749e18d9ab020b78a5b808555746b4b18d3fc033006eae3e28936"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
datapack-folder = "global_packs/required_data"
