name = "Yoinky 3"
author = "Prectriv"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9e01342c766113be62542fb6832706d73c12744cb64ed9ae7c0f0278ad75aac"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
