name = "Yoinky 4"
author = "Prectriv"
version = "4.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3c3b5e3807d97268c65fe310870078cebba1dc25115a65831e65f4fb4c78eeb"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
datapack-folder = "global_packs/required_data"
