name = "New Poinky 3D XS"
author = "xvr6"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2a154b82b8b857cc6369c0eee06770c61e7ecfe339bc50c09f6f781338e8528"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "./datapacks"
