name = "New Poinky 3D XS"
author = "xvr6"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3476ae9db0797e18b59757ca302cc99532dddf8e2fd91bca312a07f040410ad4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "./datapacks"
