name = "New Poinky 3D XS"
author = "xvr6"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7862b833a679da7a4a7c57bf503ef0e5f7d9d325373c634b64b2e377ead3a160"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "./datapacks"
