name = "New Poinky 3D XS"
author = "xvr6"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aee392467e29258a456124da1c7478705d69951b9c66e60fd5a89387630fe97e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "./datapacks"
