name = "New Poinky 3D XS"
author = "xvr6"
version = "3.1.3c"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94900561ad934ed5b7359699eedef0279a5fc39e7f85832d8d85d7b1827583d3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "./datapacks"
