name = "New Poinky 3D XS"
author = "prectriv"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44dd02730f70937901b01ae98a31c298a249dba619ff64d1958350399a023ffa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "./datapacks"
