name = "Yoinky 3"
author = "Prectriv"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b864268184ab9324b34dbe7e4d2955c4dfd95e85e8ecc72c311fd7d47b9db7fe"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["fabric"]
datapack-folder = "global_packs/required_data"
