name = "Poinky"
author = "prectriv"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a242e9cc86588dcd2f5c415863d2e3a23beb369b63890d4c04f4a0625c283283"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
