name = "Poinky"
author = "prectriv"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "002a958d1fb7baf064545d2ce7e6bfcab72e3aa551600066b7988ba2795dc6c3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
