name = "Poinky"
author = "prectriv"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a7ca4f826e6e216bf68db01e9211fc549c954b0f30ddcb17397881acd36c3b4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
